// mvp-processor/src/routes/processing/+page.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import {
    triggerModalJob,
    getModalJobs,
    cancelModalJob,
    clearCompletedJobs,
    WebSocketManager,
    formatTimestamp
  } from '$lib/utils/api';
  import { processingJobs } from '$lib/stores/processingJobs';
  import Card from '$lib/components/Card.svelte';
  import Button from '$lib/components/Button.svelte';
  import Badge from '$lib/components/Badge.svelte';
  import StatusIndicator from '$lib/components/StatusIndicator.svelte';
  import IconButton from '$lib/components/IconButton.svelte';
  
  let error: string | null = null;
  let isProcessing = false;
  let ws: WebSocketManager | null = null;
  let mounted = false;
  
  // Load existing jobs on mount
  onMount(async () => {
    mounted = true;
    
    try {
      // Connect to WebSocket for real-time updates
      const wsUrl = window.location.origin.replace('http', 'ws') + '/ws/modal-jobs';
      ws = new WebSocketManager(wsUrl);
      
      ws.connect(
        (data) => {
          // Handle job updates from WebSocket
          if (data.job || data.job_id) {
            const job = data.job || { id: data.job_id, ...data };
            processingJobs.updateJob(job.id, job);
          }
        },
        (error) => {
          console.error('WebSocket error:', error);
        }
      );
      
      // Load existing jobs
      const { jobs } = await getModalJobs();
      jobs.forEach(job => processingJobs.addJob(job));
    } catch (err) {
      console.error('Failed to load jobs:', err);
      error = 'Failed to connect to processing service';
    }
    
    // Refresh job status every 5 seconds
    const interval = setInterval(async () => {
      try {
        const { jobs } = await getModalJobs();
        jobs.forEach(job => processingJobs.updateJob(job.id, job));
      } catch (err) {
        console.error('Failed to refresh jobs:', err);
      }
    }, 5000);
    
    return () => {
      clearInterval(interval);
      ws?.disconnect();
    };
  });
  
  onDestroy(() => {
    mounted = false;
    ws?.disconnect();
  });
  
  async function handleStartInitialProcessing() {
    isProcessing = true;
    error = null;
    
    try {
      const { job_id } = await triggerModalJob({
        mode: 'initial',
        similarity_threshold: 0.25,
        sync_from_hf: true,
        upload_results: true
      });
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to start processing';
    } finally {
      isProcessing = false;
    }
  }
  
  async function handleUpdateEmbeddings() {
    isProcessing = true;
    error = null;
    
    try {
      const { job_id } = await triggerModalJob({
        mode: 'embedding-update',
        sync_from_hf: true
      });
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to update embeddings';
    } finally {
      isProcessing = false;
    }
  }
  
  async function handleCancelJob(jobId: string) {
    try {
      await cancelModalJob(jobId);
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to cancel job';
    }
  }
  
  async function handleClearCompleted() {
    try {
      await clearCompletedJobs();
      processingJobs.clearCompleted();
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to clear completed jobs';
    }
  }
  
  function getStatusColor(status: string): string {
    switch (status) {
      case 'completed': return '#22c55e';
      case 'running': return '#3b82f6';
      case 'failed': return '#ef4444';
      case 'cancelled': return '#6b7280';
      default: return '#f59e0b';
    }
  }
  
  function formatDuration(start?: number, end?: number): string {
    if (!start) return '--';
    const endTime = end || Date.now();
    const diff = Math.floor((endTime - start) / 1000);
    const mins = Math.floor(diff / 60);
    const secs = diff % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  }
  
  $: activeJobsCount = $processingJobs.filter(j => j.status === 'running' || j.status === 'queued').length;
  $: completedJobsCount = $processingJobs.filter(j => j.status === 'completed').length;
</script>

<div class="processing-page">
  <div class="header">
    <h1>Video Processing</h1>
    <p>Manage Modal cloud processing jobs for face recognition</p>
  </div>
  
  {#if error}
    <div class="error-banner">
      {error}
    </div>
  {/if}
  
  {#if activeJobsCount > 0}
    <div class="status-banner active">
      🔄 {activeJobsCount} job{activeJobsCount !== 1 ? 's' : ''} running
    </div>
  {/if}
  
  <div class="processing-grid">
    <Card>
      <div class="card-header">
        <h2>Initial Processing</h2>
        <StatusIndicator status="ready" />
      </div>
      
      <p class="description">
        Process all videos using cloud GPUs for initial face detection and recognition
      </p>
      
      <div class="controls">
        <Button
          on:click={handleStartInitialProcessing}
          disabled={isProcessing}
          loading={isProcessing}
          variant="primary"
          fullWidth
        >
          🚀 Start Processing
        </Button>
      </div>
      
      <div class="features">
        <ul>
          <li>🎬 Process all unprocessed videos</li>
          <li>👥 Detect and recognize faces</li>
          <li>⚡ Cloud GPU acceleration</li>
          <li>☁️ Automatic HuggingFace sync</li>
        </ul>
      </div>
    </Card>
    
    <Card>
      <div class="card-header">
        <h2>Embedding Update</h2>
        <StatusIndicator status="ready" />
      </div>
      
      <p class="description">
        Improve recognition accuracy by incorporating user-flagged faces into embeddings
      </p>
      
      <div class="controls">
        <Button
          on:click={handleUpdateEmbeddings}
          disabled={isProcessing}
          loading={isProcessing}
          variant="secondary"
          fullWidth
        >
          🔄 Update Embeddings
        </Button>
      </div>
      
      <div class="features">
        <ul>
          <li>🎯 Improve face recognition accuracy</li>
          <li>🏷️ Incorporate user feedback</li>
          <li>⚡ Fast embedding recalculation</li>
          <li>🔄 Automatic database rebuild</li>
        </ul>
      </div>
    </Card>
  </div>
  
  <Card>
    <div class="card-header">
      <h2>Processing Jobs</h2>
      <div class="job-stats">
        <Badge color="#3b82f6">{activeJobsCount} Active</Badge>
        <Badge color="#22c55e">{completedJobsCount} Completed</Badge>
        {#if completedJobsCount > 0}
          <Button
            size="small"
            variant="text"
            on:click={handleClearCompleted}
          >
            Clear Completed
          </Button>
        {/if}
      </div>
    </div>
    
    {#if $processingJobs.length === 0}
      <div class="empty-state">
        <p>No processing jobs yet</p>
        <p class="help">Start a processing job to see it here</p>
      </div>
    {:else}
      <div class="job-list">
        {#each $processingJobs as job}
          <div class="job-item">
            <div class="job-main">
              <div class="job-header">
                <h3>{job.mode ? job.mode.replace('-', ' ').toUpperCase() : 'Processing'}</h3>
                <Badge color={getStatusColor(job.status)}>
                  {job.status}
                </Badge>
              </div>
              
              {#if job.current_video}
                <p class="current-video">📹 {job.current_video}</p>
              {/if}
              
              {#if job.videos_processed !== undefined && job.total_videos}
                <p class="video-progress">
                  {job.videos_processed} / {job.total_videos} videos
                </p>
              {/if}
              
              <div class="progress-section">
                <div class="progress-bar">
                  <div
                    class="progress-fill"
                    style="width: {job.progress || 0}%"
                  ></div>
                </div>
                <span class="progress-text">{job.progress || 0}%</span>
              </div>
            </div>
            
            <div class="job-actions">
              {#if job.status === 'queued' || job.status === 'running'}
                <IconButton
                  icon="x-circle"
                  title="Cancel job"
                  on:click={() => handleCancelJob(job.id)}
                  disabled={job.status === 'cancelled'}
                />
              {/if}
              
              <div class="job-times">
                {#if job.created_at}
                  <span class="time-label">Created: {formatTimestamp(new Date(job.created_at).toISOString())}</span>
                {/if}
                {#if job.started_at}
                  <span class="time-label">Duration: {formatDuration(job.started_at, job.completed_at)}</span>
                {/if}
              </div>
            </div>
          </div>
        {/each}
      </div>
    {/if}
  </Card>
</div>

<style>
  .processing-page {
    max-width: 1400px;
    margin: 0 auto;
    padding: 2rem;
  }
  
  .header {
    margin-bottom: 2rem;
    
    h1 {
      font-size: 2rem;
      font-weight: 600;
      margin-bottom: 0.5rem;
      color: #1f2937;
    }
    
    p {
      color: #6b7280;
      font-size: 1.125rem;
    }
  }
  
  .error-banner {
    background: #fee2e2;
    border: 1px solid #ef4444;
    color: #991b1b;
    padding: 1rem;
    border-radius: 0.75rem;
    margin-bottom: 1.5rem;
    font-weight: 500;
  }
  
  .status-banner {
    padding: 1rem 1.5rem;
    border-radius: 0.75rem;
    margin-bottom: 1.5rem;
    font-weight: 500;
    display: flex;
    align-items: center;
    gap: 0.5rem;
    
    &.active {
      background: #dbeafe;
      border: 1px solid #3b82f6;
      color: #1d4ed8;
    }
  }
  
  .processing-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
    gap: 1.5rem;
    margin-bottom: 2rem;
  }
  
  .card-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1rem;
    
    h2 {
      font-size: 1.25rem;
      font-weight: 600;
      margin: 0;
      color: #1f2937;
    }
  }
  
  .description {
    color: #6b7280;
    margin-bottom: 1.5rem;
    line-height: 1.5;
  }
  
  .controls {
    margin-bottom: 1.5rem;
  }
  
  .features {
    ul {
      list-style: none;
      padding: 0;
      margin: 0;
      
      li {
        padding: 0.25rem 0;
        color: #6b7280;
        font-size: 0.875rem;
        
        &:before {
          content: '✓';
          color: #10b981;
          font-weight: bold;
          margin-right: 0.5rem;
        }
      }
    }
  }
  
  .job-stats {
    display: flex;
    gap: 0.5rem;
    align-items: center;
  }
  
  .empty-state {
    text-align: center;
    padding: 3rem;
    color: #9ca3af;
    
    .help {
      font-size: 0.875rem;
      margin-top: 0.5rem;
    }
  }
  
  .job-list {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }
  
  .job-item {
    border: 1px solid #e5e7eb;
    border-radius: 0.75rem;
    padding: 1.25rem;
    background: #f9fafb;
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    transition: box-shadow 0.2s ease;
    
    &:hover {
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
    }
    
    .job-main {
      flex: 1;
    }
    
    .job-header {
      display: flex;
      gap: 0.75rem;
      align-items: center;
      margin-bottom: 0.75rem;
      
      h3 {
        margin: 0;
        font-size: 1rem;
        font-weight: 600;
        color: #1f2937;
      }
    }
    
    .current-video {
      margin: 0.25rem 0;
      font-size: 0.875rem;
      color: #6b7280;
      font-weight: 500;
    }
    
    .video-progress {
      margin: 0.5rem 0;
      font-size: 0.875rem;
      color: #374151;
      font-weight: 500;
    }
    
    .progress-section {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      margin: 0.75rem 0;
      
      .progress-bar {
        flex: 1;
        height: 8px;
        background: #e5e7eb;
        border-radius: 4px;
        overflow: hidden;
        
        .progress-fill {
          height: 100%;
          background: #3b82f6;
          transition: width 0.3s ease;
        }
      }
      
      .progress-text {
        font-size: 0.875rem;
        font-weight: 600;
        color: #374151;
        min-width: 40px;
      }
    }
    
    .job-actions {
      display: flex;
      flex-direction: column;
      align-items: flex-end;
      gap: 0.5rem;
      margin-left: 1rem;
      
      .job-times {
        display: flex;
        flex-direction: column;
        align-items: flex-end;
        gap: 0.25rem;
        
        .time-label {
          font-size: 0.75rem;
          color: #6b7280;
        }
      }
    }
  }
</style>

// apps/admin/src/pages/Processing.tsx
import { useState, useEffect, useMemo, useRef, useCallback } from 'react';
import { Card, Badge, Button } from '@mv/shared';

interface ProcessingJob {
  id: string;
  mode?: string;
  status: 'queued' | 'running' | 'completed' | 'failed' | 'cancelled';
  progress: number;
  current_video?: string;
  videos_processed?: number;
  total_videos?: number;
  created_at?: string;
  started_at?: number;
  completed_at?: number;
  error?: string;
}

function getStatusVariant(status: string): 'success' | 'warning' | 'error' | 'neutral' {
  switch (status) {
    case 'completed': return 'success';
    case 'running': return 'warning';
    case 'failed': return 'error';
    default: return 'neutral';
  }
}

function getStatusColor(status: string): string {
  switch (status) {
    case 'completed': return 'bg-green-500';
    case 'running': return 'bg-blue-500';
    case 'failed': return 'bg-red-500';
    case 'cancelled': return 'bg-slate-500';
    default: return 'bg-amber-500';
  }
}

function formatDuration(start?: number, end?: number): string {
  if (!start) return '--';
  const endTime = end || Date.now();
  const diff = Math.floor((endTime - start) / 1000);
  const mins = Math.floor(diff / 60);
  const secs = diff % 60;
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}

function formatTimestamp(iso?: string): string {
  if (!iso) return '--';
  return new Date(iso).toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

export function Processing() {
  const [jobs, setJobs] = useState<ProcessingJob[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const pollingRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const activeCount = useMemo(() => jobs.filter((j) => j.status === 'running' || j.status === 'queued').length, [jobs]);
  const completedCount = useMemo(() => jobs.filter((j) => j.status === 'completed').length, [jobs]);

  const fetchJobs = useCallback(async () => {
    try {
      const res = await fetch('/api/processing/jobs');
      if (!res.ok) return;
      const data = await res.json();
      const jobList = data.jobs || data || [];
      setJobs(Array.isArray(jobList) ? jobList : []);
    } catch (e) {
      console.error('Failed to fetch jobs:', e);
    }
  }, []);

  // Initial load + polling
  useEffect(() => {
    fetchJobs();
    pollingRef.current = setInterval(fetchJobs, 5000);
    return () => {
      if (pollingRef.current) clearInterval(pollingRef.current);
    };
  }, [fetchJobs]);

  async function startInitialProcessing() {
    setIsProcessing(true);
    setError(null);
    try {
      const res = await fetch('/api/processing/trigger', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          mode: 'initial',
          similarity_threshold: 0.25,
          sync_from_hf: true,
          upload_results: true,
        }),
      });
      if (!res.ok) throw new Error('Failed to start processing');
      await fetchJobs();
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to start processing');
    } finally {
      setIsProcessing(false);
    }
  }

  async function startEmbeddingUpdate() {
    setIsProcessing(true);
    setError(null);
    try {
      const res = await fetch('/api/processing/trigger', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          mode: 'embedding-update',
          sync_from_hf: true,
        }),
      });
      if (!res.ok) throw new Error('Failed to update embeddings');
      await fetchJobs();
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to update embeddings');
    } finally {
      setIsProcessing(false);
    }
  }

  async function cancelJob(jobId: string) {
    try {
      const res = await fetch(`/api/processing/cancel/${jobId}`, { method: 'POST' });
      if (!res.ok) throw new Error('Failed to cancel job');
      await fetchJobs();
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to cancel job');
    }
  }

  async function clearCompleted() {
    try {
      const res = await fetch('/api/processing/clear-completed', { method: 'POST' });
      if (res.ok) {
        setJobs((prev) => prev.filter((j) => j.status !== 'completed'));
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to clear completed jobs');
    }
  }

  return (
    <div className="space-y-6 max-w-[1400px] mx-auto">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-slate-100">Video Processing</h1>
        <p className="text-slate-400 text-sm mt-1">Manage cloud processing jobs for face recognition</p>
      </div>

      {/* Error Banner */}
      {error && (
        <div className="bg-red-900/30 border border-red-800 text-red-400 px-4 py-3 rounded-lg text-sm font-medium">
          {error}
        </div>
      )}

      {/* Active Jobs Banner */}
      {activeCount > 0 && (
        <div className="bg-blue-900/20 border border-blue-800 text-blue-400 px-4 py-3 rounded-lg text-sm font-medium flex items-center gap-2">
          <div className="w-4 h-4 border-2 border-blue-400 border-t-transparent rounded-full animate-spin" />
          {activeCount} job{activeCount !== 1 ? 's' : ''} running
        </div>
      )}

      {/* Processing Action Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card padding="lg">
          <div className="flex justify-between items-center mb-3">
            <h2 className="text-base font-semibold text-slate-200">Initial Processing</h2>
            <span className="w-2 h-2 rounded-full bg-green-500" />
          </div>
          <p className="text-sm text-slate-400 mb-4 leading-relaxed">
            Process all videos using cloud GPUs for initial face detection and recognition
          </p>
          <Button
            variant="primary"
            onClick={startInitialProcessing}
            disabled={isProcessing}
            className="w-full mb-4"
          >
            {isProcessing ? 'Starting...' : 'Start Processing'}
          </Button>
          <ul className="space-y-1.5 text-xs text-slate-500">
            <li className="flex items-center gap-2"><span className="text-green-500">&#x2713;</span> Process all unprocessed videos</li>
            <li className="flex items-center gap-2"><span className="text-green-500">&#x2713;</span> Detect and recognize faces</li>
            <li className="flex items-center gap-2"><span className="text-green-500">&#x2713;</span> Cloud GPU acceleration</li>
            <li className="flex items-center gap-2"><span className="text-green-500">&#x2713;</span> Automatic HuggingFace sync</li>
          </ul>
        </Card>

        <Card padding="lg">
          <div className="flex justify-between items-center mb-3">
            <h2 className="text-base font-semibold text-slate-200">Embedding Update</h2>
            <span className="w-2 h-2 rounded-full bg-green-500" />
          </div>
          <p className="text-sm text-slate-400 mb-4 leading-relaxed">
            Improve recognition accuracy by incorporating user-flagged faces into embeddings
          </p>
          <Button
            variant="secondary"
            onClick={startEmbeddingUpdate}
            disabled={isProcessing}
            className="w-full mb-4"
          >
            {isProcessing ? 'Starting...' : 'Update Embeddings'}
          </Button>
          <ul className="space-y-1.5 text-xs text-slate-500">
            <li className="flex items-center gap-2"><span className="text-green-500">&#x2713;</span> Improve face recognition accuracy</li>
            <li className="flex items-center gap-2"><span className="text-green-500">&#x2713;</span> Incorporate user feedback</li>
            <li className="flex items-center gap-2"><span className="text-green-500">&#x2713;</span> Fast embedding recalculation</li>
            <li className="flex items-center gap-2"><span className="text-green-500">&#x2713;</span> Automatic database rebuild</li>
          </ul>
        </Card>
      </div>

      {/* Jobs List */}
      <Card padding="lg">
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-base font-semibold text-slate-200">Processing Jobs</h2>
          <div className="flex items-center gap-2">
            <Badge variant="warning" size="sm">{activeCount} Active</Badge>
            <Badge variant="success" size="sm">{completedCount} Completed</Badge>
            {completedCount > 0 && (
              <Button variant="ghost" size="sm" onClick={clearCompleted}>
                Clear Completed
              </Button>
            )}
          </div>
        </div>

        {jobs.length === 0 ? (
          <div className="text-center py-10 text-slate-500">
            <p className="text-sm">No processing jobs yet</p>
            <p className="text-xs mt-1">Start a processing job to see it here</p>
          </div>
        ) : (
          <div className="space-y-3">
            {jobs.map((job) => (
              <div
                key={job.id}
                className="bg-slate-950 border border-slate-800 rounded-lg p-4 flex gap-4 hover:border-slate-700 transition-colors"
              >
                {/* Main Content */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-3 mb-2">
                    <h3 className="text-sm font-semibold text-slate-200">
                      {job.mode ? job.mode.replace('-', ' ').toUpperCase() : 'Processing'}
                    </h3>
                    <Badge variant={getStatusVariant(job.status)} size="sm">
                      {job.status}
                    </Badge>
                  </div>

                  {job.current_video && (
                    <p className="text-xs text-slate-400 font-medium mb-1">{job.current_video}</p>
                  )}

                  {job.videos_processed !== undefined && job.total_videos && (
                    <p className="text-xs text-slate-300 font-medium mb-1">
                      {job.videos_processed} / {job.total_videos} videos
                    </p>
                  )}

                  {/* Progress bar */}
                  <div className="flex items-center gap-3 mt-2">
                    <div className="flex-1 h-2 bg-slate-800 rounded-full overflow-hidden">
                      <div
                        className={`h-full rounded-full transition-all duration-300 ${getStatusColor(job.status)}`}
                        style={{ width: `${job.progress || 0}%` }}
                      />
                    </div>
                    <span className="text-xs font-semibold text-slate-300 min-w-[40px]">
                      {job.progress || 0}%
                    </span>
                  </div>

                  {job.error && (
                    <p className="text-xs text-red-400 mt-2">{job.error}</p>
                  )}
                </div>

                {/* Actions & Times */}
                <div className="flex flex-col items-end gap-2 shrink-0">
                  {(job.status === 'queued' || job.status === 'running') && (
                    <Button
                      variant="destructive"
                      size="sm"
                      onClick={() => cancelJob(job.id)}
                    >
                      Cancel
                    </Button>
                  )}
                  <div className="text-right space-y-0.5">
                    {job.created_at && (
                      <p className="text-[11px] text-slate-500">Created: {formatTimestamp(job.created_at)}</p>
                    )}
                    {job.started_at && (
                      <p className="text-[11px] text-slate-500">
                        Duration: {formatDuration(job.started_at, job.completed_at)}
                      </p>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </Card>
    </div>
  );
}
