// apps/admin/src/pages/Contestants.tsx
import { useState, useMemo, useCallback } from 'react';
import { useContestants } from '@mv/shared';
import { Badge } from '@mv/shared';
import type { Contestant } from '@mv/shared';

interface Appearance {
  video_id: string;
  video_name?: string;
  timestamp: number;
  confidence: number;
}

interface ContestantStats {
  total_appearances: number;
  screen_time_seconds: number;
  videos_appeared_in: number;
}

function formatTime(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}

function formatScreenTime(seconds: number): string {
  if (seconds < 60) return `${seconds}s`;
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  if (mins < 60) return secs > 0 ? `${mins}m ${secs}s` : `${mins}m`;
  const hours = Math.floor(mins / 60);
  const remainingMins = mins % 60;
  return `${hours}h ${remainingMins}m`;
}

function getContestantInitials(contestant: Contestant): string {
  if (contestant.nickname && contestant.nickname.length <= 3) {
    return contestant.nickname;
  }
  return `#${contestant.id}`;
}

export function Contestants() {
  const { data: contestants = [], isLoading, error, refetch } = useContestants();
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedContestant, setSelectedContestant] = useState<Contestant | null>(null);
  const [appearances, setAppearances] = useState<Appearance[]>([]);
  const [stats, setStats] = useState<ContestantStats | null>(null);
  const [isLoadingAppearances, setIsLoadingAppearances] = useState(false);

  const filteredContestants = useMemo(() => {
    const query = searchQuery.toLowerCase().trim();
    if (!query) return contestants;
    return contestants.filter(
      (c: Contestant) =>
        c.name.toLowerCase().includes(query) ||
        c.nickname.toLowerCase().includes(query) ||
        String(c.id).includes(query),
    );
  }, [contestants, searchQuery]);

  const loadAppearances = useCallback(async (contestant: Contestant) => {
    setIsLoadingAppearances(true);
    try {
      const res = await fetch(`/api/recognition/results?contestant_id=${contestant.id}`);
      if (res.ok) {
        const data = await res.json();
        const results = data.results || data || [];
        setAppearances(
          results.map((r: Record<string, unknown>) => ({
            video_id: r.video_id,
            video_name: `Video ${r.video_id}`,
            timestamp: r.timestamp as number,
            confidence: r.confidence as number,
          })),
        );
        const uniqueVideos = new Set(results.map((r: Record<string, unknown>) => r.video_id));
        setStats({
          total_appearances: results.length,
          screen_time_seconds: results.length * 2,
          videos_appeared_in: uniqueVideos.size,
        });
      }
    } catch {
      setAppearances([]);
      setStats(null);
    } finally {
      setIsLoadingAppearances(false);
    }
  }, []);

  const openModal = useCallback(
    (contestant: Contestant) => {
      setSelectedContestant(contestant);
      setAppearances([]);
      setStats(null);
      loadAppearances(contestant);
    },
    [loadAppearances],
  );

  const closeModal = useCallback(() => {
    setSelectedContestant(null);
    setAppearances([]);
    setStats(null);
  }, []);

  return (
    <div className="p-6 max-w-[1400px] mx-auto">
      {/* Header */}
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-slate-100 mb-1">Contestant Directory</h1>
        <p className="text-slate-400 text-sm">Browse all 96 contestants and view their appearance history</p>
      </div>

      {/* Search bar */}
      <div className="flex gap-4 items-center mb-6 flex-wrap">
        <div className="relative flex-1 max-w-[400px] min-w-[200px]">
          <span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500 text-sm">Search</span>
          <input
            type="text"
            className="w-full pl-16 pr-8 py-2.5 bg-slate-900 border border-slate-800 rounded-lg text-slate-200 text-sm placeholder:text-slate-600 focus:outline-none focus:border-orange-500 focus:ring-1 focus:ring-orange-500/30"
            placeholder="by name or nickname..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
          {searchQuery && (
            <button
              className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500 hover:text-slate-200"
              onClick={() => setSearchQuery('')}
            >
              x
            </button>
          )}
        </div>
        <Badge variant="neutral" size="md">
          {filteredContestants.length} of {contestants.length} contestants
        </Badge>
      </div>

      {/* Content */}
      {isLoading ? (
        <div className="flex flex-col items-center justify-center py-12 text-slate-400">
          <div className="w-10 h-10 border-3 border-slate-700 border-t-orange-500 rounded-full animate-spin mb-4" />
          <p>Loading contestants...</p>
        </div>
      ) : error ? (
        <div className="flex flex-col items-center justify-center py-12 text-slate-400">
          <p className="text-red-400 mb-4">Failed to load contestants</p>
          <button
            className="px-4 py-2 bg-slate-800 text-slate-200 border border-slate-700 rounded-md hover:bg-orange-600 hover:border-orange-600 transition-colors"
            onClick={() => refetch()}
          >
            Retry
          </button>
        </div>
      ) : filteredContestants.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-12 text-slate-400">
          <p className="mb-4">No contestants found matching &quot;{searchQuery}&quot;</p>
          <button
            className="px-4 py-2 bg-slate-800 text-slate-200 border border-slate-700 rounded-md hover:bg-orange-600 hover:border-orange-600 transition-colors"
            onClick={() => setSearchQuery('')}
          >
            Clear search
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-[repeat(auto-fill,minmax(180px,1fr))] gap-4">
          {filteredContestants.map((contestant: Contestant) => (
            <button
              key={contestant.id}
              className="flex flex-col bg-slate-900 border border-slate-800 rounded-lg overflow-hidden cursor-pointer transition-all text-left p-0 hover:border-orange-500 hover:-translate-y-1 hover:shadow-[0_8px_25px_rgba(0,0,0,0.3)]"
              onClick={() => openModal(contestant)}
            >
              <div className="aspect-square bg-gradient-to-br from-slate-800 to-slate-900 flex items-center justify-center relative">
                <span className="text-3xl font-bold text-white/90">{getContestantInitials(contestant)}</span>
                {contestant.has_embedding && (
                  <span
                    className="absolute bottom-2 right-2 bg-green-500 text-white w-5 h-5 rounded-full flex items-center justify-center text-xs"
                    title="Has face embedding"
                  >
                    &#10003;
                  </span>
                )}
              </div>
              <div className="p-3">
                <div className="font-semibold text-sm text-slate-200 truncate">{contestant.name}</div>
                <div className="text-xs text-slate-400 truncate">{contestant.nickname}</div>
                {contestant.age && <div className="text-xs text-slate-500 mt-0.5">{contestant.age} years old</div>}
              </div>
            </button>
          ))}
        </div>
      )}

      {/* Detail Modal */}
      {selectedContestant && (
        <div
          className="fixed inset-0 bg-black/85 flex items-center justify-center z-50 p-6 backdrop-blur-sm"
          onClick={closeModal}
          onKeyDown={(e) => e.key === 'Escape' && closeModal()}
          role="button"
          tabIndex={0}
        >
          <div
            className="bg-slate-900 rounded-xl max-w-[600px] w-full max-h-[85vh] overflow-y-auto relative border border-slate-800"
            onClick={(e) => e.stopPropagation()}
            role="dialog"
            aria-modal="true"
          >
            {/* Close button */}
            <button
              className="absolute top-4 right-4 bg-slate-800 border-none text-slate-400 text-lg cursor-pointer z-10 w-8 h-8 rounded-full flex items-center justify-center hover:bg-red-500 hover:text-white transition-colors"
              onClick={closeModal}
              aria-label="Close modal"
            >
              x
            </button>

            <div className="p-6">
              {/* Modal Header */}
              <div className="flex gap-5 mb-6">
                <div className="w-[100px] h-[100px] shrink-0 bg-gradient-to-br from-slate-700 to-slate-800 rounded-lg flex items-center justify-center">
                  <span className="text-4xl font-bold text-white/90">
                    {getContestantInitials(selectedContestant)}
                  </span>
                </div>
                <div className="flex-1">
                  <h2 className="text-xl font-bold text-slate-100 mb-1">{selectedContestant.name}</h2>
                  <p className="text-base text-slate-400 mb-3">{selectedContestant.nickname}</p>
                  <div className="flex items-center gap-3 flex-wrap">
                    <Badge variant="neutral" size="sm">#{selectedContestant.id}</Badge>
                    {selectedContestant.age && (
                      <span className="text-xs text-slate-500">{selectedContestant.age} years old</span>
                    )}
                    {selectedContestant.has_embedding && (
                      <Badge variant="success" size="sm">Has Embedding</Badge>
                    )}
                  </div>
                </div>
              </div>

              {/* Stats */}
              <div className="grid grid-cols-3 gap-3 mb-6">
                {isLoadingAppearances ? (
                  <div className="col-span-3 text-center py-4 text-slate-500">Loading stats...</div>
                ) : stats ? (
                  <>
                    <div className="text-center p-4 bg-slate-800 rounded-lg">
                      <span className="block text-xl font-bold text-orange-400 leading-none mb-1">
                        {stats.total_appearances}
                      </span>
                      <span className="block text-[10px] text-slate-500 uppercase tracking-wider">Appearances</span>
                    </div>
                    <div className="text-center p-4 bg-slate-800 rounded-lg">
                      <span className="block text-xl font-bold text-orange-400 leading-none mb-1">
                        {formatScreenTime(stats.screen_time_seconds)}
                      </span>
                      <span className="block text-[10px] text-slate-500 uppercase tracking-wider">Screen Time</span>
                    </div>
                    <div className="text-center p-4 bg-slate-800 rounded-lg">
                      <span className="block text-xl font-bold text-orange-400 leading-none mb-1">
                        {stats.videos_appeared_in}
                      </span>
                      <span className="block text-[10px] text-slate-500 uppercase tracking-wider">Videos</span>
                    </div>
                  </>
                ) : (
                  <div className="col-span-3 text-center py-4 text-slate-500">No appearance data available</div>
                )}
              </div>

              {/* Appearances */}
              <div>
                <h3 className="text-sm font-semibold text-slate-200 mb-4">Appearance History</h3>
                {isLoadingAppearances ? (
                  <div className="flex items-center gap-3 py-4 text-slate-500">
                    <div className="w-5 h-5 border-2 border-slate-700 border-t-orange-500 rounded-full animate-spin" />
                    <span>Loading appearances...</span>
                  </div>
                ) : appearances.length === 0 ? (
                  <div className="text-center py-6 bg-slate-800 rounded-lg text-slate-400">
                    <p>No recorded appearances yet.</p>
                    <p className="text-xs text-slate-500 mt-2">
                      Appearances are recorded when videos are processed with face recognition.
                    </p>
                  </div>
                ) : (
                  <div className="flex flex-col gap-2 max-h-[250px] overflow-y-auto">
                    {appearances.map((appearance, idx) => (
                      <button
                        key={idx}
                        className="flex justify-between items-center px-4 py-3 bg-slate-800 border border-transparent rounded-md cursor-pointer transition-all text-left w-full hover:bg-slate-700 hover:border-orange-500 group"
                        onClick={() => {
                          window.location.href = `/player?video=${appearance.video_id}&t=${appearance.timestamp}`;
                        }}
                      >
                        <div className="flex flex-col gap-0.5">
                          <span className="font-medium text-slate-200 text-xs">
                            {appearance.video_name || `Video ${appearance.video_id}`}
                          </span>
                          <span className="text-[10px] text-slate-500">@ {formatTime(appearance.timestamp)}</span>
                        </div>
                        <div className="flex items-center gap-3">
                          <Badge
                            variant={
                              appearance.confidence > 0.85
                                ? 'success'
                                : appearance.confidence > 0.7
                                  ? 'warning'
                                  : 'neutral'
                            }
                            size="sm"
                          >
                            {(appearance.confidence * 100).toFixed(0)}%
                          </Badge>
                          <span className="text-slate-500 transition-transform group-hover:translate-x-1 group-hover:text-orange-400">
                            &rarr;
                          </span>
                        </div>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// mvp-processor/src/routes/contestants/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { Card, Badge, Input } from '$lib/components';

  interface Contestant {
    id: string;
    number: number;
    name: string;
    nickname: string;
    age?: number;
    has_photos?: boolean;
    has_embedding?: boolean;
  }

  interface Appearance {
    video_id: string;
    video_name?: string;
    timestamp: number;
    confidence: number;
  }

  interface ContestantStats {
    total_appearances: number;
    screen_time_seconds: number;
    videos_appeared_in: number;
  }

  let contestants: Contestant[] = [];
  let filteredContestants: Contestant[] = [];
  let searchQuery = '';
  let isLoading = true;
  let error: string | null = null;
  
  let selectedContestant: Contestant | null = null;
  let selectedContestantAppearances: Appearance[] = [];
  let selectedContestantStats: ContestantStats | null = null;
  let isLoadingAppearances = false;

  async function loadContestants() {
    try {
      isLoading = true;
      error = null;
      const response = await fetch('/api/contestants');
      if (response.ok) {
        contestants = await response.json();
        filteredContestants = contestants;
      } else {
        error = 'Failed to load contestants';
      }
    } catch (e) {
      console.error('Failed to load contestants:', e);
      error = 'Failed to load contestants';
    } finally {
      isLoading = false;
    }
  }

  function handleSearch() {
    const query = searchQuery.toLowerCase().trim();
    if (!query) {
      filteredContestants = contestants;
      return;
    }
    filteredContestants = contestants.filter(c =>
      c.name.toLowerCase().includes(query) ||
      c.nickname.toLowerCase().includes(query) ||
      String(c.number).includes(query)
    );
  }

  async function loadContestantAppearances(contestant: Contestant) {
    try {
      isLoadingAppearances = true;
      const response = await fetch(`/api/recognition/results?contestant_id=${contestant.id}`);
      if (response.ok) {
        const data = await response.json();
        const results = data.results || data || [];
        
        selectedContestantAppearances = results.map((r: any) => ({
          video_id: r.video_id,
          video_name: `Video ${r.video_id}`,
          timestamp: r.timestamp,
          confidence: r.confidence
        }));

        const uniqueVideos = new Set(results.map((r: any) => r.video_id));
        selectedContestantStats = {
          total_appearances: results.length,
          screen_time_seconds: results.length * 2,
          videos_appeared_in: uniqueVideos.size
        };
      }
    } catch (e) {
      console.error('Failed to load appearances:', e);
      selectedContestantAppearances = [];
      selectedContestantStats = null;
    } finally {
      isLoadingAppearances = false;
    }
  }

  async function openModal(contestant: Contestant) {
    selectedContestant = contestant;
    selectedContestantAppearances = [];
    selectedContestantStats = null;
    await loadContestantAppearances(contestant);
  }

  function closeModal() {
    selectedContestant = null;
    selectedContestantAppearances = [];
    selectedContestantStats = null;
  }

  function formatTime(seconds: number): string {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  }

  function formatScreenTime(seconds: number): string {
    if (seconds < 60) return `${seconds}s`;
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    if (mins < 60) return secs > 0 ? `${mins}m ${secs}s` : `${mins}m`;
    const hours = Math.floor(mins / 60);
    const remainingMins = mins % 60;
    return `${hours}h ${remainingMins}m`;
  }

  function navigateToVideo(videoId: string, timestamp: number) {
    goto(`/player?video=${videoId}&t=${timestamp}`);
  }

  function getContestantInitials(contestant: Contestant): string {
    if (contestant.nickname && contestant.nickname.length <= 3) {
      return contestant.nickname;
    }
    return `#${contestant.number}`;
  }

  onMount(() => {
    loadContestants();
  });

  $: if (searchQuery !== undefined) {
    handleSearch();
  }
</script>

<svelte:head>
  <title>Contestants - Face Recognition Dashboard</title>
</svelte:head>

<div class="contestants-page">
  <div class="page-header">
    <h1>👥 Contestant Directory</h1>
    <p class="page-description">Browse all 96 contestants and view their appearance history</p>
  </div>

  <div class="search-bar">
    <div class="search-input-wrapper">
      <span class="search-icon">🔍</span>
      <input
        type="text"
        class="search-input"
        placeholder="Search by name or nickname..."
        bind:value={searchQuery}
      />
      {#if searchQuery}
        <button class="clear-btn" on:click={() => searchQuery = ''}>✕</button>
      {/if}
    </div>
    <Badge variant="secondary" size="md">
      {filteredContestants.length} of {contestants.length} contestants
    </Badge>
  </div>

  {#if isLoading}
    <div class="loading-state">
      <div class="spinner"></div>
      <p>Loading contestants...</p>
    </div>
  {:else if error}
    <div class="error-state">
      <p>❌ {error}</p>
      <button class="btn-retry" on:click={loadContestants}>Retry</button>
    </div>
  {:else if filteredContestants.length === 0}
    <div class="empty-state">
      <p>No contestants found matching "{searchQuery}"</p>
      <button class="btn-secondary" on:click={() => searchQuery = ''}>Clear search</button>
    </div>
  {:else}
    <div class="contestants-grid">
      {#each filteredContestants as contestant (contestant.id)}
        <button class="contestant-card" on:click={() => openModal(contestant)}>
          <div class="contestant-photo">
            <span class="photo-initials">{getContestantInitials(contestant)}</span>
            {#if contestant.has_embedding}
              <span class="embedding-badge" title="Has face embedding">✓</span>
            {/if}
          </div>
          <div class="contestant-info">
            <div class="contestant-name">{contestant.name}</div>
            <div class="contestant-nickname">{contestant.nickname}</div>
            {#if contestant.age}
              <div class="contestant-age">{contestant.age} years old</div>
            {/if}
          </div>
        </button>
      {/each}
    </div>
  {/if}

  {#if selectedContestant}
    <div 
      class="modal-overlay" 
      on:click={closeModal} 
      on:keydown={(e) => e.key === 'Escape' && closeModal()} 
      role="button" 
      tabindex="0"
    >
      <div 
        class="modal" 
        on:click|stopPropagation 
        on:keydown={() => {}}
        role="dialog" 
        aria-modal="true" 
        tabindex="-1"
      >
        <button class="modal-close" on:click={closeModal} aria-label="Close modal">✕</button>
        
        <div class="modal-content">
          <div class="modal-header">
            <div class="modal-photo">
              <span class="photo-initials-large">{getContestantInitials(selectedContestant)}</span>
            </div>
            
            <div class="modal-title">
              <h2>{selectedContestant.name}</h2>
              <p class="modal-nickname">{selectedContestant.nickname}</p>
              <div class="modal-meta">
                <Badge variant="primary" size="sm">#{selectedContestant.number}</Badge>
                {#if selectedContestant.age}
                  <span class="meta-age">{selectedContestant.age} years old</span>
                {/if}
                {#if selectedContestant.has_embedding}
                  <Badge variant="success" size="sm">Has Embedding</Badge>
                {/if}
              </div>
            </div>
          </div>

          <div class="modal-stats">
            {#if isLoadingAppearances}
              <div class="stats-loading">Loading stats...</div>
            {:else if selectedContestantStats}
              <div class="stat-card">
                <span class="stat-value">{selectedContestantStats.total_appearances}</span>
                <span class="stat-label">Appearances</span>
              </div>
              <div class="stat-card">
                <span class="stat-value">{formatScreenTime(selectedContestantStats.screen_time_seconds)}</span>
                <span class="stat-label">Screen Time</span>
              </div>
              <div class="stat-card">
                <span class="stat-value">{selectedContestantStats.videos_appeared_in}</span>
                <span class="stat-label">Videos</span>
              </div>
            {:else}
              <div class="stats-empty">No appearance data available</div>
            {/if}
          </div>

          <div class="modal-appearances">
            <h3>📍 Appearance History</h3>
            
            {#if isLoadingAppearances}
              <div class="appearances-loading">
                <div class="spinner-small"></div>
                <span>Loading appearances...</span>
              </div>
            {:else if selectedContestantAppearances.length === 0}
              <div class="appearances-empty">
                <p>No recorded appearances yet.</p>
                <p class="hint">Appearances are recorded when videos are processed with face recognition.</p>
              </div>
            {:else}
              <div class="appearances-list">
                {#each selectedContestantAppearances as appearance}
                  <button 
                    class="appearance-item"
                    on:click={() => navigateToVideo(appearance.video_id, appearance.timestamp)}
                  >
                    <div class="appearance-info">
                      <span class="appearance-video">📹 {appearance.video_name || `Video ${appearance.video_id}`}</span>
                      <span class="appearance-time">@ {formatTime(appearance.timestamp)}</span>
                    </div>
                    <div class="appearance-meta">
                      <Badge 
                        variant={appearance.confidence > 0.85 ? 'success' : appearance.confidence > 0.7 ? 'warning' : 'secondary'} 
                        size="sm"
                      >
                        {(appearance.confidence * 100).toFixed(0)}%
                      </Badge>
                      <span class="appearance-arrow">→</span>
                    </div>
                  </button>
                {/each}
              </div>
            {/if}
          </div>
        </div>
      </div>
    </div>
  {/if}
</div>

<style>
  .contestants-page {
    padding: var(--space-6);
    max-width: 1400px;
    margin: 0 auto;
  }

  .page-header {
    margin-bottom: var(--space-6);
  }

  .page-header h1 {
    font-size: var(--text-h2-size);
    font-weight: 700;
    margin: 0 0 var(--space-2);
  }

  .page-description {
    color: var(--text-secondary);
    font-size: var(--text-body-size);
    margin: 0;
  }

  .search-bar {
    display: flex;
    gap: var(--space-4);
    align-items: center;
    margin-bottom: var(--space-6);
    flex-wrap: wrap;
  }

  .search-input-wrapper {
    position: relative;
    flex: 1;
    max-width: 400px;
    min-width: 200px;
  }

  .search-icon {
    position: absolute;
    left: var(--space-3);
    top: 50%;
    transform: translateY(-50%);
    font-size: 1rem;
    opacity: 0.5;
  }

  .search-input {
    width: 100%;
    padding: var(--space-3) var(--space-10);
    background-color: var(--bg-secondary);
    border: 1px solid var(--border-default);
    border-radius: var(--radius-lg);
    color: var(--text-primary);
    font-size: var(--text-body-size);
  }

  .search-input:focus {
    outline: none;
    border-color: var(--color-primary-500);
    box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.2);
  }

  .clear-btn {
    position: absolute;
    right: var(--space-3);
    top: 50%;
    transform: translateY(-50%);
    background: none;
    border: none;
    color: var(--text-tertiary);
    cursor: pointer;
    padding: var(--space-1);
  }

  .clear-btn:hover {
    color: var(--text-primary);
  }

  .loading-state,
  .error-state,
  .empty-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: var(--space-12);
    text-align: center;
    color: var(--text-secondary);
  }

  .spinner {
    width: 40px;
    height: 40px;
    border: 3px solid var(--border-default);
    border-top-color: var(--color-primary-500);
    border-radius: 50%;
    animation: spin 1s linear infinite;
    margin-bottom: var(--space-4);
  }

  .spinner-small {
    width: 20px;
    height: 20px;
    border: 2px solid var(--border-default);
    border-top-color: var(--color-primary-500);
    border-radius: 50%;
    animation: spin 1s linear infinite;
  }

  @keyframes spin {
    to { transform: rotate(360deg); }
  }

  .btn-retry,
  .btn-secondary {
    margin-top: var(--space-4);
    padding: var(--space-2) var(--space-4);
    background-color: var(--bg-tertiary);
    color: var(--text-primary);
    border: 1px solid var(--border-default);
    border-radius: var(--radius-md);
    cursor: pointer;
    transition: var(--transition-colors);
  }

  .btn-retry:hover,
  .btn-secondary:hover {
    background-color: var(--color-primary-600);
    border-color: var(--color-primary-600);
  }

  .contestants-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
    gap: var(--space-4);
  }

  .contestant-card {
    display: flex;
    flex-direction: column;
    background-color: var(--bg-secondary);
    border: 1px solid var(--border-default);
    border-radius: var(--radius-lg);
    overflow: hidden;
    cursor: pointer;
    transition: var(--transition-all);
    text-align: left;
    padding: 0;
  }

  .contestant-card:hover {
    border-color: var(--color-primary-500);
    transform: translateY(-4px);
    box-shadow: 0 8px 25px rgba(0, 0, 0, 0.3);
  }

  .contestant-photo {
    aspect-ratio: 1;
    background: linear-gradient(135deg, var(--color-primary-900), var(--color-secondary-900));
    display: flex;
    align-items: center;
    justify-content: center;
    position: relative;
  }

  .photo-initials {
    font-size: 2rem;
    font-weight: 700;
    color: white;
    opacity: 0.9;
  }

  .photo-initials-large {
    font-size: 3rem;
    font-weight: 700;
    color: white;
    opacity: 0.9;
  }

  .embedding-badge {
    position: absolute;
    bottom: var(--space-2);
    right: var(--space-2);
    background: var(--color-success-500);
    color: white;
    width: 20px;
    height: 20px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 0.75rem;
  }

  .contestant-info {
    padding: var(--space-3);
  }

  .contestant-name {
    font-weight: 600;
    font-size: var(--text-body-size);
    color: var(--text-primary);
    margin-bottom: var(--space-0-5);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .contestant-nickname {
    font-size: var(--text-body-sm-size);
    color: var(--text-secondary);
    margin-bottom: var(--space-1);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .contestant-age {
    font-size: var(--text-body-xs-size);
    color: var(--text-tertiary);
  }

  .modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.85);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: var(--z-modal);
    padding: var(--space-6);
    backdrop-filter: blur(4px);
  }

  .modal {
    background: var(--bg-secondary);
    border-radius: var(--radius-xl);
    max-width: 600px;
    width: 100%;
    max-height: 85vh;
    overflow-y: auto;
    position: relative;
    border: 1px solid var(--border-default);
  }

  .modal-close {
    position: absolute;
    top: var(--space-4);
    right: var(--space-4);
    background: var(--bg-tertiary);
    border: none;
    color: var(--text-secondary);
    font-size: 1.25rem;
    cursor: pointer;
    z-index: 1;
    width: 32px;
    height: 32px;
    border-radius: var(--radius-full);
    display: flex;
    align-items: center;
    justify-content: center;
    transition: var(--transition-colors);
  }

  .modal-close:hover {
    background: var(--color-error-500);
    color: white;
  }

  .modal-content {
    padding: var(--space-6);
  }

  .modal-header {
    display: flex;
    gap: var(--space-5);
    margin-bottom: var(--space-6);
  }

  .modal-photo {
    width: 100px;
    height: 100px;
    flex-shrink: 0;
    background: linear-gradient(135deg, var(--color-primary-800), var(--color-secondary-800));
    border-radius: var(--radius-lg);
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .modal-title {
    flex: 1;
  }

  .modal-title h2 {
    font-size: var(--text-h3-size);
    font-weight: 700;
    margin: 0 0 var(--space-1);
  }

  .modal-nickname {
    font-size: var(--text-body-lg-size);
    color: var(--text-secondary);
    margin: 0 0 var(--space-3);
  }

  .modal-meta {
    display: flex;
    align-items: center;
    gap: var(--space-3);
    flex-wrap: wrap;
  }

  .meta-age {
    font-size: var(--text-body-sm-size);
    color: var(--text-tertiary);
  }

  .modal-stats {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: var(--space-3);
    margin-bottom: var(--space-6);
  }

  .stat-card {
    text-align: center;
    padding: var(--space-4);
    background: var(--bg-tertiary);
    border-radius: var(--radius-lg);
  }

  .stat-value {
    display: block;
    font-size: var(--text-h3-size);
    font-weight: 700;
    color: var(--color-primary-400);
    line-height: 1;
    margin-bottom: var(--space-1);
  }

  .stat-label {
    display: block;
    font-size: var(--text-body-xs-size);
    color: var(--text-tertiary);
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .stats-loading,
  .stats-empty {
    grid-column: 1 / -1;
    text-align: center;
    padding: var(--space-4);
    color: var(--text-tertiary);
  }

  .modal-appearances h3 {
    font-size: var(--text-h5-size);
    font-weight: 600;
    margin: 0 0 var(--space-4);
  }

  .appearances-loading {
    display: flex;
    align-items: center;
    gap: var(--space-3);
    padding: var(--space-4);
    color: var(--text-tertiary);
  }

  .appearances-empty {
    text-align: center;
    padding: var(--space-6);
    background: var(--bg-tertiary);
    border-radius: var(--radius-lg);
    color: var(--text-secondary);
  }

  .appearances-empty .hint {
    font-size: var(--text-body-sm-size);
    color: var(--text-tertiary);
    margin-top: var(--space-2);
  }

  .appearances-list {
    display: flex;
    flex-direction: column;
    gap: var(--space-2);
    max-height: 250px;
    overflow-y: auto;
  }

  .appearance-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: var(--space-3) var(--space-4);
    background: var(--bg-tertiary);
    border: 1px solid transparent;
    border-radius: var(--radius-md);
    cursor: pointer;
    transition: var(--transition-all);
    text-align: left;
    width: 100%;
  }

  .appearance-item:hover {
    background: var(--color-primary-900);
    border-color: var(--color-primary-500);
  }

  .appearance-info {
    display: flex;
    flex-direction: column;
    gap: var(--space-0-5);
  }

  .appearance-video {
    font-weight: 500;
    color: var(--text-primary);
    font-size: var(--text-body-sm-size);
  }

  .appearance-time {
    font-size: var(--text-body-xs-size);
    color: var(--text-tertiary);
  }

  .appearance-meta {
    display: flex;
    align-items: center;
    gap: var(--space-3);
  }

  .appearance-arrow {
    color: var(--text-tertiary);
    transition: transform var(--duration-fast);
  }

  .appearance-item:hover .appearance-arrow {
    transform: translateX(4px);
    color: var(--color-primary-400);
  }

  @media (max-width: 768px) {
    .contestants-grid {
      grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
    }

    .modal-header {
      flex-direction: column;
      align-items: center;
      text-align: center;
    }

    .modal-meta {
      justify-content: center;
    }

    .modal-stats {
      grid-template-columns: 1fr;
    }
  }
</style>
